apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://geek-cookbook.github.io/k8s-helm
    chart: uptime-kuma
    targetRevision: 1.5.0
    helm:
      values: |
        service:
          type: ClusterIP
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 1Gi
  destination:
    server: https://192.168.1.23:6444
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true